from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.pdfgen import canvas


OUTPUT = Path("output/pdf/suntax_sample_salary_certificate_2025.pdf")


def row(pdf, y, label, value, width):
    pdf.setStrokeColor(colors.HexColor("#D7DEE7"))
    pdf.line(20 * mm, y - 5 * mm, width - 20 * mm, y - 5 * mm)
    pdf.setFillColor(colors.HexColor("#5B6472"))
    pdf.setFont("Helvetica", 8.5)
    pdf.drawString(22 * mm, y, label)
    pdf.setFillColor(colors.HexColor("#10233D"))
    pdf.setFont("Helvetica-Bold", 9.5)
    pdf.drawRightString(width - 22 * mm, y, value)
    return y - 10 * mm


def main():
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    pdf = canvas.Canvas(str(OUTPUT), pagesize=A4)
    width, height = A4

    pdf.setFillColor(colors.HexColor("#12395B"))
    pdf.rect(0, height - 42 * mm, width, 42 * mm, fill=1, stroke=0)
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 21)
    pdf.drawString(20 * mm, height - 22 * mm, "Sample salary certificate")
    pdf.setFont("Helvetica", 9)
    pdf.drawString(20 * mm, height - 30 * mm, "Fictional test document - not valid for tax filing")

    y = height - 55 * mm
    pdf.setFillColor(colors.HexColor("#10233D"))
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawString(20 * mm, y, "Tax year 2025")
    y -= 10 * mm

    pdf.setFillColor(colors.HexColor("#EAF2F8"))
    pdf.roundRect(20 * mm, y - 27 * mm, width - 40 * mm, 27 * mm, 3 * mm, fill=1, stroke=0)
    pdf.setFillColor(colors.HexColor("#12395B"))
    pdf.setFont("Helvetica-Bold", 9)
    pdf.drawString(25 * mm, y - 9 * mm, "TEST DATA ONLY")
    pdf.setFont("Helvetica", 8.5)
    pdf.drawString(25 * mm, y - 17 * mm, "This document contains invented names and amounts for SunTax upload testing.")
    y -= 40 * mm

    pdf.setFillColor(colors.HexColor("#10233D"))
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(20 * mm, y, "Employee")
    y -= 8 * mm
    y = row(pdf, y, "Name", "Alex Example", width)
    y = row(pdf, y, "Address", "12 Example Lane, 8000 Zurich", width)
    y = row(pdf, y, "Date of birth", "15 March 1990", width)
    y = row(pdf, y, "AHV number", "756.0000.0000.00 (fictional)", width)

    y -= 8 * mm
    pdf.setFillColor(colors.HexColor("#10233D"))
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(20 * mm, y, "Employer and income")
    y -= 8 * mm
    y = row(pdf, y, "Employer", "Example Services AG", width)
    y = row(pdf, y, "Employment period", "01.01.2025 - 31.12.2025", width)
    y = row(pdf, y, "Gross annual salary", "CHF 95,000.00", width)
    y = row(pdf, y, "AHV / IV / EO contributions", "CHF 5,510.00", width)
    y = row(pdf, y, "Unemployment insurance", "CHF 1,045.00", width)
    y = row(pdf, y, "Pension fund contribution", "CHF 4,750.00", width)
    y = row(pdf, y, "Net salary paid", "CHF 83,695.00", width)

    pdf.setFillColor(colors.HexColor("#5B6472"))
    pdf.setFont("Helvetica", 7.5)
    disclaimer = "Generated by SunTax for local testing. It is not an official Swiss salary certificate."
    pdf.drawCentredString(width / 2, 17 * mm, disclaimer)
    pdf.drawRightString(width - 20 * mm, 10 * mm, "Page 1 of 1")
    pdf.save()


if __name__ == "__main__":
    main()
